from typing import overload
import wx

class AuiPaneInfo:
    def IsShown(self) -> bool: ...
    def Show(self, show: bool = ...) -> None: ...

class AuiManager(wx.EvtHandler):
    @overload
    def GetPane(self, window: wx.Window) -> AuiPaneInfo: ...
    @overload
    def GetPane(self, name: str) -> AuiPaneInfo: ...
    def Update(self) -> None: ...

class AuiManagerEvent(wx.Event): ...
