AUI_BUTTON_CLOSE = 101
AUI_BUTTON_CUSTOM1 = 201
AUI_BUTTON_CUSTOM2 = 202
AUI_BUTTON_CUSTOM3 = 203
AUI_BUTTON_DOWN = 110
AUI_BUTTON_LEFT = 107

AUI_BUTTON_MAXIMIZE_RESTORE = 102

AUI_BUTTON_MINIMIZE = 103
AUI_BUTTON_OPTIONS = 105
AUI_BUTTON_PIN = 104
AUI_BUTTON_RIGHT = 108

AUI_BUTTON_STATE_CHECKED = 32
AUI_BUTTON_STATE_DISABLED = 8
AUI_BUTTON_STATE_HIDDEN = 16
AUI_BUTTON_STATE_HOVER = 2
AUI_BUTTON_STATE_NORMAL = 0
AUI_BUTTON_STATE_PRESSED = 4

AUI_BUTTON_UP = 109
AUI_BUTTON_WINDOWLIST = 106

AUI_DOCKART_ACTIVE_CAPTION_COLOUR = 7

AUI_DOCKART_ACTIVE_CAPTION_GRADIENT_COLOUR = 8

AUI_DOCKART_ACTIVE_CAPTION_TEXT_COLOUR = 11

AUI_DOCKART_BACKGROUND_COLOUR = 5

AUI_DOCKART_BORDER_COLOUR = 13

AUI_DOCKART_CAPTION_FONT = 15
AUI_DOCKART_CAPTION_SIZE = 1

AUI_DOCKART_GRADIENT_TYPE = 16

AUI_DOCKART_GRIPPER_COLOUR = 14
AUI_DOCKART_GRIPPER_SIZE = 2

AUI_DOCKART_INACTIVE_CAPTION_COLOUR = 9

AUI_DOCKART_INACTIVE_CAPTION_GRADIENT_COLOUR = 10

AUI_DOCKART_INACTIVE_CAPTION_TEXT_COLOUR = 12

AUI_DOCKART_PANE_BORDER_SIZE = 3

AUI_DOCKART_PANE_BUTTON_SIZE = 4

AUI_DOCKART_SASH_COLOUR = 6
AUI_DOCKART_SASH_SIZE = 0

AUI_DOCK_BOTTOM = 3
AUI_DOCK_CENTER = 5
AUI_DOCK_CENTRE = 5
AUI_DOCK_LEFT = 4
AUI_DOCK_NONE = 0
AUI_DOCK_RIGHT = 2
AUI_DOCK_TOP = 1

AUI_GRADIENT_HORIZONTAL = 2
AUI_GRADIENT_NONE = 0
AUI_GRADIENT_VERTICAL = 1

AUI_MGR_ALLOW_ACTIVE_PANE = 2

AUI_MGR_ALLOW_FLOATING = 1

AUI_MGR_DEFAULT = 201

AUI_MGR_HINT_FADE = 64

AUI_MGR_LIVE_RESIZE = 256

AUI_MGR_NO_VENETIAN_BLINDS_FADE = 128

AUI_MGR_RECTANGLE_HINT = 32

AUI_MGR_TRANSPARENT_DRAG = 4
AUI_MGR_TRANSPARENT_HINT = 8

AUI_MGR_VENETIAN_BLINDS_HINT = 16

AUI_NB_BOTTOM = 8

AUI_NB_CLOSE_BUTTON = 1024

AUI_NB_CLOSE_ON_ACTIVE_TAB = 2048

AUI_NB_CLOSE_ON_ALL_TABS = 4096

AUI_NB_DEFAULT_STYLE = 10545

AUI_NB_LEFT = 2

AUI_NB_MIDDLE_CLICK_CLOSE = 8192

AUI_NB_RIGHT = 4

AUI_NB_SCROLL_BUTTONS = 256

AUI_NB_TAB_EXTERNAL_MOVE = 64

AUI_NB_TAB_FIXED_WIDTH = 128

AUI_NB_TAB_MOVE = 32
AUI_NB_TAB_SPLIT = 16

AUI_NB_TOP = 1

AUI_NB_WINDOWLIST_BUTTON = 512

AUI_ORIENTATION_MASK = 160

AUI_TBART_GRIPPER_SIZE = 1

AUI_TBART_OVERFLOW_SIZE = 2

AUI_TBART_SEPARATOR_SIZE = 0

AUI_TBTOOL_TEXT_BOTTOM = 3
AUI_TBTOOL_TEXT_LEFT = 0
AUI_TBTOOL_TEXT_RIGHT = 1
AUI_TBTOOL_TEXT_TOP = 2

AUI_TB_DEFAULT_STYLE = 0

AUI_TB_GRIPPER = 8
AUI_TB_HORIZONTAL = 128

AUI_TB_HORZ_LAYOUT = 64
AUI_TB_HORZ_TEXT = 65

AUI_TB_NO_AUTORESIZE = 4
AUI_TB_NO_TOOLTIPS = 2

AUI_TB_OVERFLOW = 16

AUI_TB_PLAIN_BACKGROUND = 256

AUI_TB_TEXT = 1
AUI_TB_VERTICAL = 32

wxEVT_AUINOTEBOOK_ALLOW_DND = 10240

wxEVT_AUINOTEBOOK_BEGIN_DRAG = 10236

wxEVT_AUINOTEBOOK_BG_DCLICK = 10241

wxEVT_AUINOTEBOOK_BUTTON = 10235

wxEVT_AUINOTEBOOK_DRAG_DONE = 10242
wxEVT_AUINOTEBOOK_DRAG_MOTION = 10239

wxEVT_AUINOTEBOOK_END_DRAG = 10237

wxEVT_AUINOTEBOOK_PAGE_CHANGED = 10234
wxEVT_AUINOTEBOOK_PAGE_CHANGING = 10233
wxEVT_AUINOTEBOOK_PAGE_CLOSE = 10231
wxEVT_AUINOTEBOOK_PAGE_CLOSED = 10232

wxEVT_AUINOTEBOOK_TAB_MIDDLE_DOWN = 10244
wxEVT_AUINOTEBOOK_TAB_MIDDLE_UP = 10243

wxEVT_AUINOTEBOOK_TAB_RIGHT_DOWN = 10246
wxEVT_AUINOTEBOOK_TAB_RIGHT_UP = 10245

wxEVT_AUITOOLBAR_BEGIN_DRAG = 10251

wxEVT_AUITOOLBAR_MIDDLE_CLICK = 10250

wxEVT_AUITOOLBAR_OVERFLOW_CLICK = 10248

wxEVT_AUITOOLBAR_RIGHT_CLICK = 10249

wxEVT_AUITOOLBAR_TOOL_DROPDOWN = 10247

wxEVT_AUI_FIND_MANAGER = 10230

wxEVT_AUI_PANE_ACTIVATED = 10228
wxEVT_AUI_PANE_BUTTON = 10224
wxEVT_AUI_PANE_CLOSE = 10225
wxEVT_AUI_PANE_MAXIMIZE = 10226
wxEVT_AUI_PANE_RESTORE = 10227

wxEVT_AUI_RENDER = 10229
